"""create tables

Revision ID: 74217ecdf6b8
Revises: 
Create Date: 2025-02-18 07:17:45.302544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74217ecdf6b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('monday', sa.Integer(), nullable=False),
    sa.Column('tuesday', sa.Integer(), nullable=False),
    sa.Column('wednesday', sa.Integer(), nullable=False),
    sa.Column('thursday', sa.Integer(), nullable=False),
    sa.Column('friday', sa.Integer(), nullable=False),
    sa.Column('saturday', sa.Integer(), nullable=False),
    sa.Column('sunday', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_index(op.f('ix_calendar_service_id'), 'calendar', ['service_id'], unique=False)
    op.create_table('calendar_dates',
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('exception_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('service_id', 'date')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('route_short_name', sa.String(), nullable=False),
    sa.Column('route_long_name', sa.String(), nullable=True),
    sa.Column('route_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index(op.f('ix_routes_route_id'), 'routes', ['route_id'], unique=False)
    op.create_table('routes_jp',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('route_update_date', sa.String(), nullable=True),
    sa.Column('origin_stop', sa.String(), nullable=False),
    sa.Column('via_stop', sa.String(), nullable=True),
    sa.Column('destination_stop', sa.String(), nullable=False),
    sa.Column('jp_parent_route_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index(op.f('ix_routes_jp_route_id'), 'routes_jp', ['route_id'], unique=False)
    op.create_table('stop_times',
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('trip_id', 'stop_sequence')
    )
    op.create_table('stops',
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('stop_name', sa.String(), nullable=False),
    sa.Column('stop_lat', sa.Float(), nullable=False),
    sa.Column('stop_lon', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_index(op.f('ix_stops_stop_id'), 'stops', ['stop_id'], unique=False)
    op.create_table('trips',
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('trip_headsign', sa.String(), nullable=True),
    sa.Column('direction_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_index(op.f('ix_trips_trip_id'), 'trips', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_trip_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_stops_stop_id'), table_name='stops')
    op.drop_table('stops')
    op.drop_table('stop_times')
    op.drop_index(op.f('ix_routes_jp_route_id'), table_name='routes_jp')
    op.drop_table('routes_jp')
    op.drop_index(op.f('ix_routes_route_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_table('calendar_dates')
    op.drop_index(op.f('ix_calendar_service_id'), table_name='calendar')
    op.drop_table('calendar')
    # ### end Alembic commands ###
