"""create tables

Revision ID: 9a72708fe54d
Revises: 40e64d25a3f1
Create Date: 2025-02-09 05:56:17.105382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a72708fe54d'
down_revision: Union[str, None] = '40e64d25a3f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes_jp',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('route_update_date', sa.String(), nullable=True),
    sa.Column('origin_stop', sa.String(), nullable=False),
    sa.Column('via_stop', sa.String(), nullable=True),
    sa.Column('destination_stop', sa.String(), nullable=False),
    sa.Column('jp_parent_route_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index(op.f('ix_routes_jp_route_id'), 'routes_jp', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_jp_route_id'), table_name='routes_jp')
    op.drop_table('routes_jp')
    # ### end Alembic commands ###
